package StudyPass;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class SubjectRepositoryImpl implements IRepository<Subject> {
    private java.sql.Connection con;
    public SubjectRepositoryImpl(){
        this.con = SocialNetworkService.getConnection();
    }

    @Override
    public List<Subject> findAll() throws SQLException {
        List<Subject> subjects = new ArrayList<>();

        Statement st = this.con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM subjects");

        while(rs.next()){
            Subject s =  bdToEntity(rs);
            subjects.add(s);
        }
        return subjects;
    }

    @Override
    public void save(Subject subject) throws SQLException {
        if (subject.getId() == -1){
            ResultSet rs;
            PreparedStatement st = null;
            String query = "INSERT INTO subjects (name) VALUES (?)";
            //Fijáos en Statement.RETURN_GENERATED_KEYS. Permite recuperar el campo ID autogenerado por MySql
            st = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);

            st.setString(1, subject.getName());

            st.executeUpdate();

            rs = st.getGeneratedKeys();

            if (rs.next()){
                subject.setId(rs.getInt(1));
                System.out.println("Autogenerated ID:  " + subject.getId());
            }
        }else{
            PreparedStatement st = con.prepareStatement("UPDATE subjects SET username = ? WHERE id = ?");
            st.setString(1, subject.getName());
            st.setInt(2, subject.getId());

            st.executeUpdate();
        }
    }

    @Override
    public void delete(Subject subject) throws SQLException {
        PreparedStatement st = con.prepareStatement("DELETE FROM subjects WHERE id = ?");
        st.setInt(1, subject.getId());
        st.executeUpdate();
        st.close();
    }

    @Override
    public Subject bdToEntity(ResultSet rs) throws SQLException {
        return null;
    }

    public Subject findByFlashCard(FlashCard flashCard) throws SQLException{
        PreparedStatement st = con.prepareStatement("SELECT * FROM subjects WHERE id = ? ");
        st.setInt(1, flashCard.getId());

        ResultSet rs = st.executeQuery();
        Subject s = null;
        if (rs.next()){
            s = bdToEntity(rs);
        }
        return s;
    }
}
